Gitted driver-git-remote auto-commit from root@okahack:/sysconf

diff --git a/tree/usr/bin/gitted b/tree/usr/bin/gitted
--- a/tree/usr/bin/gitted
+++ b/tree/usr/bin/gitted
@@ -682,6 +682,189 @@ script_command_show() {
     fi
 }
 
+#
+# Command: script_command_expand [options] <branch1> [<branch2>] ...
+#
+# Expand '*' and '**' patterns on branch list
+#
+# Options:
+#
+#   --usage-command NAME
+#
+#   --existing
+#       Fail if any given branch does not exist.
+#
+#   --commitable
+#       Restrict to branches where commit is supported by the driver
+#
+#   --resettable
+#       Restrict to branches where reset is supported by the driver
+#
+# <branch> list is printed back to stdout, after expanding as follow:
+#
+#   First, a list of (*/suffix) is made from state configs.
+#   In this list, each driver is called for a ref list.
+#   That list is filtered after the ending part (following the driver prefix).
+#
+#   That will be merged with the branch list of any driver within "a/b".
+#
+#   For each driver found, the "list" command is executed on the driver.
+#   Restrict the list to any part after the driver path, replacing "**" with "*"
+#   (from ex above: "b/*/suffix" or "*/suffix" or "*/suffix")
+#
+# Branch pattern examples:
+#
+#   some/branch   -> left untouched
+#   dir/*         -> "*" is expanded to all descendants that exist PHYSICALLY
+#   dir/*/suffix  -> same, restricting to suffix
+#   a/b/**/suffix -> when "**" is encountered, the most specific driver
+#                     is identified (be it "a" or "a/b" or "a/b/c/d).
+#
+#
+##
+script_command_expand() {
+    local _usage_name=
+    local _existing_only=no
+    local _config
+    while [ -n "$1" ]; do
+        case "$1" in
+            --usage-command) _usage_name=$2; shift 2 ;;
+            --existing) _existing_only=yes; shift ;;
+            --committable) export GITTED_CONFIG_DRIVER_LIST_ONLY_COMMITABLE=yes; shift ;;
+            --resettable) export GITTED_CONFIG_DRIVER_LIST_ONLY_RESETTABLE=yes; shift ;;
+            -h|--help) script_command_help expand; return ;;
+            --) shift; break ;;
+            -*) script_eval_common_option "$1"; shift ;;
+            *) break ;;
+        esac
+    done
+
+    while [ -n "$1" ]; do
+
+        [[ "$1" =~ ^(([-a-zA-Z0-9.,!+=_@^%]+|\*\*?)(/|$))+$ ]] \
+            || nef_fatal_usage_command "$_usage_name" "invalid <state branch> pattern: $1"
+
+        [[ "$1" =~ /$ ]] \
+            && nef_fatal_usage_command "$_usage_name" "invalid trailing slash for <state branch> pattern: $1"
+
+        if [[ "$1" =~ \* ]]; then
+
+            local _branch=
+
+            if [[ "$1" =~ \*\* ]]; then   ## branch has a "**": ignore existing branches altogether
+
+                local _driver_branches=
+                local _pattern="${1//\*\*/*}"
+                local _ifs="$IFS"; IFS='*';
+                local _parts=($_pattern); IFS="$_ifs"
+                local _base=${_parts[0]}
+
+                local _driver_branch=$(script_driver_root_branch $_base)
+                # nef_log "Found driver branch: $_driver_branch"
+
+                if [ -n "$_driver_branch" ]; then
+                    ## $_base is below a driver domain: single driver
+
+                    _driver_branches="$_driver_branches $_driver_branch"
+                    ## local _nested=${_base#${_driver_branch}/};
+                    ## nef_log "Nested branch is: $_nested"
+                else
+                    ## $_base (before first '*') is not below a driver demain
+                    ## Which means we need a config search to grab all driver domains under $_base
+
+                    _configs=$(find $GITTED_STATE_CONFIG_DIR/$_base -name '*.config' -printf "%P\n")
+                    for _config in $_configs; do
+                        # nef_log "driver domain under: ${_base}${_config%.config}"
+                        _driver_branches="$_driver_branches ${_base}${_config%.config}"
+                    done
+
+                fi
+
+                local _regex="^${_pattern//\*/.+}$"
+                local _ok=
+
+                for _branch in $_driver_branches; do
+                    # nef_log "Expanding: $1: calling driver: $_branch"
+                    (
+                        script_load_state_config $_branch
+                        local _status=$?
+                        if [ $_status = 2 ]; then
+                            nef_log -v "State is NOT ENABLED (from config), ignoring: $_branch"
+                        else
+                            if [ $_status -ne 0 ]; then
+                                nef_fatal --warn "could not load driver for branch, ignoring it: $_branch"
+                            else
+                                export GITTED_CONFIG_DRIVER_ACTION=list
+                                export GITTED_CONFIG_DRIVER_LIST_ONLY_COMMITABLE=
+                                export GITTED_CONFIG_DRIVER_LIST_ONLY_RESETTABLE=
+                                local _nested_branch=
+                                local _nested_branches=
+                                nef_log "nesting: $_branch"
+                                _nested_branches=$(script_call_driver)
+
+                                if  [ $? -eq 2 ]; then  ## exit code 2 means dirMode is disabled:
+
+                                    [[ $_branch =~ $_regex ]] && echo $_branch
+
+                                elif  [ $? -eq 3 ]; then
+
+                                    ## exit code 2 means dirMode is disabled AND
+                                    # committable/resettable condition is not met
+                                    # -> ignore the branch
+                                    true
+
+                                else
+
+                                    for _nested_branch in $_nested_branches; do
+
+                                        _last_branch=${_branch}/${_nested_branch}
+                                        if [[ $_last_branch =~ $_regex ]]; then
+                                            # nef_log "Expanding: $1: to branch: $_last_branch (included)"
+                                            echo $_last_branch
+                                            # else
+                                            # nef_log "Expanding: $1: to branch: $_last_branch (filtered out)"
+                                        fi
+                                    done
+                                    [ -n "$_nested_branch" ]
+                                fi
+                            fi
+                        fi
+                        # nef_log "NOTICE: Driver returns no branch on: $_branch"
+                    )
+                    if [ $? -eq 0 ]; then
+                        _ok=yes
+                    fi
+                done
+
+                [ -z "$_ok" ] \
+                    && nef_fatal_usage_command "$_usage_name" "pattern does not match any branch: $1"
+
+
+            else  ## branch has a "*", not "**": match against refs/heads/ files
+
+                cd $GIT_DIR/refs/heads
+
+                # echo command: find -path "./$1" -type f >&2
+                for _branch in $(find -path "./$1" -type f); do
+                    echo ${_branch#./}
+                done
+                [ -z "$_branch" ] && nef_fatal_usage_command "$_usage_name" "pattern does not match any branch: $1"
+            fi
+
+        else      ## no "*" or "**" in branch: just check --existing
+
+            [ -d $GIT_DIR/refs/heads/$1 ] \
+                && nef_fatal_usage_command "$_usage_name" "branch is a directory: $1"
+
+            if [ $_existing_only = yes ]; then
+                [ -f $GIT_DIR/refs/heads/$1 ] \
+                    || nef_fatal_usage_command "$_usage_name" "--existing given but branch does not exist: $1"
+            fi
+            echo "$1"
+        fi
+        shift
+    done
+}
 
 ######################################################################
 # COMMANDS: GIT INTEGRATION
@@ -942,189 +1125,6 @@ script_make_ref_date_prefix() {
     echo refs/gitted/transaction/${_prefix:0:-6}
 }
 
-#
-# Command: script_command_expand [options] <branch1> [<branch2>] ...
-#
-# Expand '*' and '**' patterns on branch list
-#
-# Options:
-#
-#   --usage-command NAME
-#
-#   --existing
-#       Fail if any given branch does not exist.
-#
-#   --commitable
-#       Restrict to branches where commit is supported by the driver
-#
-#   --resettable
-#       Restrict to branches where reset is supported by the driver
-#
-# <branch> list is printed back to stdout, after expanding as follow:
-#
-#   First, a list of (*/suffix) is made from state configs.
-#   In this list, each driver is called for a ref list.
-#   That list is filtered after the ending part (following the driver prefix).
-#
-#   That will be merged with the branch list of any driver within "a/b".
-#
-#   For each driver found, the "list" command is executed on the driver.
-#   Restrict the list to any part after the driver path, replacing "**" with "*"
-#   (from ex above: "b/*/suffix" or "*/suffix" or "*/suffix")
-#
-# Branch pattern examples:
-#
-#   some/branch   -> left untouched
-#   dir/*         -> "*" is expanded to all descendants that exist PHYSICALLY
-#   dir/*/suffix  -> same, restricting to suffix
-#   a/b/**/suffix -> when "**" is encountered, the most specific driver
-#                     is identified (be it "a" or "a/b" or "a/b/c/d).
-#
-#
-##
-script_command_expand() {
-    local _usage_name=
-    local _existing_only=no
-    local _config
-    while [ -n "$1" ]; do
-        case "$1" in
-            --usage-command) _usage_name=$2; shift 2 ;;
-            --existing) _existing_only=yes; shift ;;
-            --committable) export GITTED_CONFIG_DRIVER_LIST_ONLY_COMMITABLE=yes; shift ;;
-            --resettable) export GITTED_CONFIG_DRIVER_LIST_ONLY_RESETTABLE=yes; shift ;;
-            -h|--help) script_command_help expand; return ;;
-            --) shift; break ;;
-            -*) script_eval_common_option "$1"; shift ;;
-            *) break ;;
-        esac
-    done
-
-    while [ -n "$1" ]; do
-
-        [[ "$1" =~ ^(([-a-zA-Z0-9.,!+=_@^%]+|\*\*?)(/|$))+$ ]] \
-            || nef_fatal_usage_command "$_usage_name" "invalid <state branch> pattern: $1"
-
-        [[ "$1" =~ /$ ]] \
-            && nef_fatal_usage_command "$_usage_name" "invalid trailing slash for <state branch> pattern: $1"
-
-        if [[ "$1" =~ \* ]]; then
-
-            local _branch=
-
-            if [[ "$1" =~ \*\* ]]; then   ## branch has a "**": ignore existing branches altogether
-
-                local _driver_branches=
-                local _pattern="${1//\*\*/*}"
-                local _ifs="$IFS"; IFS='*';
-                local _parts=($_pattern); IFS="$_ifs"
-                local _base=${_parts[0]}
-
-                local _driver_branch=$(script_driver_root_branch $_base)
-                # nef_log "Found driver branch: $_driver_branch"
-
-                if [ -n "$_driver_branch" ]; then
-                    ## $_base is below a driver domain: single driver
-
-                    _driver_branches="$_driver_branches $_driver_branch"
-                    ## local _nested=${_base#${_driver_branch}/};
-                    ## nef_log "Nested branch is: $_nested"
-                else
-                    ## $_base (before first '*') is not below a driver demain
-                    ## Which means we need a config search to grab all driver domains under $_base
-
-                    _configs=$(find $GITTED_STATE_CONFIG_DIR/$_base -name '*.config' -printf "%P\n")
-                    for _config in $_configs; do
-                        # nef_log "driver domain under: ${_base}${_config%.config}"
-                        _driver_branches="$_driver_branches ${_base}${_config%.config}"
-                    done
-
-                fi
-
-                local _regex="^${_pattern//\*/.+}$"
-                local _ok=
-
-                for _branch in $_driver_branches; do
-                    # nef_log "Expanding: $1: calling driver: $_branch"
-                    (
-                        script_load_state_config $_branch
-                        local _status=$?
-                        if [ $_status = 2 ]; then
-                            nef_log -v "State is NOT ENABLED (from config), ignoring: $_branch"
-                        else
-                            if [ $_status -ne 0 ]; then
-                                nef_fatal --warn "could not load driver for branch, ignoring it: $_branch"
-                            else
-                                export GITTED_CONFIG_DRIVER_ACTION=list
-                                export GITTED_CONFIG_DRIVER_LIST_ONLY_COMMITABLE=
-                                export GITTED_CONFIG_DRIVER_LIST_ONLY_RESETTABLE=
-                                local _nested_branch=
-                                local _nested_branches=
-                                nef_log "nesting: $_branch"
-                                _nested_branches=$(script_call_driver)
-
-                                if  [ $? -eq 2 ]; then  ## exit code 2 means dirMode is disabled:
-
-                                    [[ $_branch =~ $_regex ]] && echo $_branch
-
-                                elif  [ $? -eq 3 ]; then
-
-                                    ## exit code 2 means dirMode is disabled AND
-                                    # committable/resettable condition is not met
-                                    # -> ignore the branch
-                                    true
-
-                                else
-
-                                    for _nested_branch in $_nested_branches; do
-
-                                        _last_branch=${_branch}/${_nested_branch}
-                                        if [[ $_last_branch =~ $_regex ]]; then
-                                            # nef_log "Expanding: $1: to branch: $_last_branch (included)"
-                                            echo $_last_branch
-                                            # else
-                                            # nef_log "Expanding: $1: to branch: $_last_branch (filtered out)"
-                                        fi
-                                    done
-                                    [ -n "$_nested_branch" ]
-                                fi
-                            fi
-                        fi
-                        # nef_log "NOTICE: Driver returns no branch on: $_branch"
-                    )
-                    if [ $? -eq 0 ]; then
-                        _ok=yes
-                    fi
-                done
-
-                [ -z "$_ok" ] \
-                    && nef_fatal_usage_command "$_usage_name" "pattern does not match any branch: $1"
-
-
-            else  ## branch has a "*", not "**": match against refs/heads/ files
-
-                cd $GIT_DIR/refs/heads
-
-                # echo command: find -path "./$1" -type f >&2
-                for _branch in $(find -path "./$1" -type f); do
-                    echo ${_branch#./}
-                done
-                [ -z "$_branch" ] && nef_fatal_usage_command "$_usage_name" "pattern does not match any branch: $1"
-            fi
-
-        else      ## no "*" or "**" in branch: just check --existing
-
-            [ -d $GIT_DIR/refs/heads/$1 ] \
-                && nef_fatal_usage_command "$_usage_name" "branch is a directory: $1"
-
-            if [ $_existing_only = yes ]; then
-                [ -f $GIT_DIR/refs/heads/$1 ] \
-                    || nef_fatal_usage_command "$_usage_name" "--existing given but branch does not exist: $1"
-            fi
-            echo "$1"
-        fi
-        shift
-    done
-}
 
 # usage: script_driver_root_branch <state branch>
 #
