improvements

diff --git a/tree/usr/bin/sysconf b/tree/usr/bin/sysconf
--- a/tree/usr/bin/sysconf
+++ b/tree/usr/bin/sysconf
@@ -222,8 +222,8 @@ load_environment_for_conf_rec()
     if [ -r environment.rc ]; then
 	nef_log -v "Loading environment: $config"
         . environment.rc
-    # else
-    #     nef_log -v "Environment not defined: $config"
+        # else
+        #     nef_log -v "Environment not defined: $config"
     fi
 }
 
@@ -338,6 +338,33 @@ sysconf_require_packages()
         # sysconf_apt-get install --yes --no-upgrade $_packages
         sysconf_apt-get install --yes --force-yes -o Dpkg::Options::=--force-confdef --no-upgrade $_packages
     fi
+}
+sysconf_fix_directory()
+{
+    local _dir="$1"
+    local _mode="$2"
+    local _ownership="$3"
+
+    if [ ! -d "$_dir" ]; then
+        echo "Creating missing directory: $_dir"
+        mkdir -p "$_dir"
+        [ -n "$_mode" ] && chmod $_mode "$_dir"
+        [ -n "$_ownership" ] && chown "$_ownership" "$_dir"
+    fi
+}
+sysconf_fix_user()
+{
+    local _name="$1"
+    shift
+
+    grep -q ^$_name: /etc/passwd || {
+        echo "Creating missing user: $_name"
+        useradd -m "$@" $_name
+        mkdir -p ~$_name/.ssh
+        chmod 750 ~$_name/.ssh
+        cp ~root/.ssh/authorized_keys ~$_name/.ssh/
+        chown -R $_name:$_name ~$_name
+    }
 }
 
 ######################################################################
